用户->CLS_WgtSystemSetting:点击规则更新按钮

CLS_WgtSystemSetting->CLS_WgtSystemSetting:on_btn_allupdate_clicked()
activate CLS_WgtSystemSetting

CLS_WgtSystemSetting->CLS_WgtSystemSetting:SaveUserInfo()
activate CLS_WgtSystemSetting
note right of CLS_WgtSystemSetting:SaveUserInfo功能\n保存界面用户信息到\nCLS_RuleUpdateManager
deactivate CLS_WgtSystemSetting

CLS_WgtSystemSetting->MainWindow:emit SigAllUpdate()
MainWindow->MainWindow:SlotAllUpdate()
activate MainWindow
MainWindow->CLS_RuleUpdateManager:run()
note right of MainWindow:在线程中执行规则更新
MainWindow->CLS_WgtSystemSetting
deactivate MainWindow

CLS_WgtSystemSetting->用户
deactivate CLS_WgtSystemSetting


group 线程
activate CLS_RuleUpdateManager

CLS_RuleUpdateManager->CLS_WebServiceManager:GetToken()
CLS_WebServiceManager->CLS_WebServiceManager:SendPost()

CLS_RuleUpdateManager->CLS_WebServiceManager:UpdateRule()
CLS_WebServiceManager->CLS_WebServiceManager:SendPost()

CLS_RuleUpdateManager->CLS_WgtSystemSetting:SlotViewRule()
note right of CLS_RuleUpdateManager:更新规则完成后展示数据

deactivate CLS_RuleUpdateManager
end